pipeline {
    agent any

    tools {
        jdk 'jdk21'
    }

    stages {

        stage('Build') {
            steps {
                sh 'java -version'
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
